import json
import os

# Directory containing the language files
lang_dir = "../p3/libs/lang/"

# Translations dictionary: key -> {lang_code: translation}
translations = {
    "needed_requirements_footer": {
        "am": "እነዚህ አስፈላጊ ባህሪዎች መጀመሪያ ይገጠሙታል፣ ከዚያ ዋናው ስክሪፕት ይቀጥላል።",
        "ar": "سيتم تثبيت هذه الميزات المطلوبة أولاً، ثم سيستمر البرنامج الرئيسي.",
        "az": "Bu tələb olunan xüsusiyyətlər əvvəlcə quraşdırılacaq, sonra əsas skript davam edəcəkdir.",
        "bg": "Тези необходими функции ще бъдат инсталирани първо, след което основният скрипт ще продължи.",
        "bn": "এই প্রয়োজনীয় বৈশিষ্ট্যগুলি প্রথমে ইনস্টল করা হবে, তারপর প্রধান স্ক্রিপ্ট চলতে থাকবে।",
        "bs": "Ove obavezne osobine će biti instalirane prvo, a zatim će glavni skript nastaviti.",
        "cs": "Tyto požadované funkce budou nainstalovány jako první, poté bude pokračovat hlavní skript.",
        "da": "Disse påkrevede funktioner vil blive installeret først, derefter vil hovedscriptet fortsætte.",
        "de": "Diese erforderlichen Funktionen werden zuerst installiert, dann wird das Hauptskript fortgesetzt.",
        "el": "Αυτές οι απαιτούμενες λειτουργίες θα εγκατασταθούν πρώτα, στη συνέχεια το κύριο σενάριο θα συνεχιστεί.",
        "es": "Estas funciones necesarias se instalarán primero, luego continuará el script principal.",
        "et": "Need nõutavad funktsioonid paigaldatakse esmalt, seejärel jätkub peamine skript.",
        "fa": "این ویژگی های مورد نیاز ابتدا نصب خواهند شد، سپس اسکریپت اصلی ادامه خواهد یافت.",
        "fi": "Nämä vaaditut ominaisuudet asennetaan ensin, minkä jälkeen pääskripti jatkuu.",
        "fr": "Ces fonctionnalités requises seront installées en premier, puis le script principal continuera.",
        "ga": "Suiteofar na gné riachtanacha seo ar dtús, ansin leanfaidh an príomhscript ar aghaidh.",
        "he": "תכונות נדרשות אלה יותקנו תחילה, ואז הסקריפט הראשי יימשך.",
        "hi": "ये आवश्यक विशेषताएं पहले स्थापित की जाएंगी, फिर मुख्य स्क्रिप्ट जारी रहेगी।",
        "hr": "Ove obavezne osobine će biti instalirane prvo, a zatim će se glavni skript nastaviti.",
        "hu": "Ezek a szükséges funkciók először telepítésre kerülnek, majd a fő szkript folytatódik.",
        "hy": "Այս անհրաժեշտ գործառույթները կտեղադրվեն առաջին հերթին, ապա հիմնական սկրիպտը կշարունակվի:",
        "id": "Fitur-fitur yang diperlukan ini akan diinstal terlebih dahulu, kemudian skrip utama akan berlanjut.",
        "is": "Þessir nauðsynlegu eiginleikar verða settir upp fyrst, síðan mun aðalskriftið halda áfram.",
        "it": "Queste funzioni necessarie verranno installate prima, quindi lo script principale continuerà.",
        "ja": "これらの必要な機能がまずインストールされ、その後、メインスクリプトが続行されます。",
        "ka": "ეს საჭირო ფუნქციები ჯერ დაინსტალირდება, შემდეგ მთავარი სკრიპტი გაგრძელდება.",
        "km": "មុខងារដែលចាំបាច់ទាំងនេះនឹងត្រូវបានដំឡើងដំបូង បន្ទាប់មក ស្គ្រីបបន្ថែមនឹងបន្ត។",
        "ko": "이러한 필수 기능이 먼저 설치되고 메인 스크립트가 계속됩니다.",
        "lo": "ຄຸນສົມບັດທີ່ຈໍາເປັນເຫຼົ່ານີ້ຈະຖືກຕິດຕັ້ງກ່ອນ, ຫຼັງຈາກນັ້ນ ສະຄິບທີ່ຕົ້ນຕໍຈະສືບຕໍ່ໄປ.",
        "lt": "Šios reikalingos funkcijos bus sumontuotos pirmiausia, tada tęsis pagrindinė skripta.",
        "lv": "Šīs nepieciešamās funkcijas tiks instalētas vispirms, tad turpināsies galvenais skripts.",
        "mn": "Эдгээр шаардлагатай функцууд эхлээд суулгагдаж, дараа нь үндсэн скрипт үргэлжлүүлнэ.",
        "ms": "Fitur-fitur yang diperlukan ini akan dipasang terlebih dahulu, kemudian skrip utama akan dilanjutkan.",
        "my": "ဤလိုအပ်သည့် အင်္ဂါရပ်များ ကို ဦးစွာ ထည့်သွင်းမည်ဖြစ်ပြီး၊ ထို့နောက် အဓိက စာသားများ သည် ဆက်လက်မည်ဖြစ်သည်။",
        "nb": "Disse nødvendige funksjonene vil bli installert først, deretter vil hovedskriptet fortsette.",
        "ne": "यी आवश्यक सुविधाहरू पहिले स्थापन गरिनेछन्, त्यसपछि मुख्य स्क्रिप्ट जारी रहनेछ।",
        "nl": "Deze vereiste functies worden eerst geïnstalleerd, waarna het hoofdscript wordt voortgezet.",
        "pl": "Te wymagane funkcje będą zainstalowane najpierw, a następnie główny skrypt będzie kontynuować.",
        "pt": "Esses recursos necessários serão instalados primeiro, depois o script principal continuará.",
        "ro": "Aceste funcții necesare vor fi instalate mai întâi, apoi scriptul principal va continua.",
        "ru": "Эти необходимые функции будут установлены в первую очередь, а затем основной скрипт продолжит работу.",
        "sk": "Tieto potrebné funkcie budú nainštalované ako prvé, potom bude pokračovať hlavný skript.",
        "sl": "Te potrebne funkcije bodo najprej nameščene, nato pa se bo glavni skript nadaljeval.",
        "sq": "Këto veçori të nevojshme do të instalohen fillimisht, pastaj skripti kryesor do të vazhdojë.",
        "sr": "Ове потребне функције ће бити инсталиране прво, а затим ће главна скрипта наставити.",
        "sv": "Dessa obligatoriska funktioner kommer att installeras först, sedan fortsätter huvudskriptet.",
        "sw": "Vipengele hivi vya mahitaji vitakamatia kwanza, kisha hati kuu itaendelea.",
        "ta": "இந்த தேவையான அம்சங்கள் முதலில் நிறுவப்படும், பிறகு முக்கிய திரைப்பதிவு தொடரும்.",
        "tg": "Ин хусусиятҳои талаботӣ аввал насб шудаанд, баъди он раёи асосӣ идома хоҳад ёфт.",
        "th": "ฟีเจอร์ที่จำเป็นเหล่านี้จะถูกติดตั้งก่อน จากนั้นสคริปต์หลักจะดำเนินการต่อ",
        "tl": "Ang mga kinakailangang feature na ito ay ilalagay muna, pagkatapos ang pangunahing script ay magpapatuloy.",
        "tr": "Bu gerekli özellikler önce yüklenecek, sonra ana betiği devam edecektir.",
        "uk": "Ці необхідні функції будуть встановлені спочатку, потім основний скрипт продовжиться.",
        "ur": "یہ ضروری خصوصیات پہلے انسٹال کی جائیں گی، پھر اہم اسکرپٹ جاری رہے گی۔",
        "uz": "Bu kerakli xususiyatlar avval o'rnatiladi, so'ng asosiy skript davom etadi.",
        "vi": "Các tính năng cần thiết này sẽ được cài đặt trước, sau đó tập lệnh chính sẽ tiếp tục.",
        "zh": "这些必需的功能将首先安装，然后主脚本将继续进行。",
    },
    "libvirt_desc": {
        "am": "virt-manager፣ libvirt እና qemu ይጭኑ እና ይዋቅሩ።",
        "ar": "تثبيت وتكوين virt-manager و libvirt و qemu.",
        "az": "virt-manager, libvirt və qemu quraşdırın və konfiqurasiya edin.",
        "bg": "Инсталирайте и конфигурирайте virt-manager, libvirt и qemu.",
        "bn": "virt-manager, libvirt এবং qemu ইনস্টল এবং কনফিগার করুন।",
        "bs": "Instalirajte i konfigurujte virt-manager, libvirt i qemu.",
        "cs": "Nainstalujte a nakonfigurujte virt-manager, libvirt a qemu.",
        "da": "Installer og konfigurer virt-manager, libvirt og qemu.",
        "de": "Installieren und konfigurieren Sie virt-manager, libvirt und qemu.",
        "el": "Εγκαταστήστε και διαμορφώστε virt-manager, libvirt και qemu.",
        "es": "Instale y configure virt-manager, libvirt y qemu.",
        "et": "Paigaldage ja konfigureerige virt-manager, libvirt ja qemu.",
        "fa": "virt-manager، libvirt و qemu را نصب و پیکربندی کنید.",
        "fi": "Asenna ja määritä virt-manager, libvirt ja qemu.",
        "fr": "Installez et configurez virt-manager, libvirt et qemu.",
        "ga": "Suiteáil agus cumraigh virt-manager, libvirt agus qemu.",
        "he": "התקן והגדר את virt-manager, libvirt ו-qemu.",
        "hi": "virt-manager, libvirt और qemu को इंस्टॉल और कॉन्फ़िगर करें।",
        "hr": "Instalirajte i konfigurujte virt-manager, libvirt i qemu.",
        "hu": "Telepítse és konfigurálja a virt-manager, libvirt és qemu alkalmazást.",
        "hy": "Տեղադրեք և կազմավորեք virt-manager, libvirt և qemu:",
        "id": "Pasang dan konfigurasikan virt-manager, libvirt, dan qemu.",
        "is": "Settu upp og stilltu virt-manager, libvirt og qemu.",
        "it": "Installa e configura virt-manager, libvirt e qemu.",
        "ja": "virt-manager、libvirt、qemuをインストールおよび構成します。",
        "ka": "დაიდეგე და გააკონფიგურე virt-manager, libvirt და qemu.",
        "km": "ដំឡើង និងកំណត់ virt-manager, libvirt និង qemu។",
        "ko": "virt-manager, libvirt 및 qemu를 설치하고 구성합니다.",
        "lo": "ຕິດຕັ້ງ ແລະ ກຳນົດຄ່າ virt-manager, libvirt ແລະ qemu.",
        "lt": "Įdiekite ir sukonfigūruokite virt-manager, libvirt ir qemu.",
        "lv": "Instalējiet un konfigurējiet virt-manager, libvirt un qemu.",
        "mn": "virt-manager, libvirt болон qemu-г суулгаж, тохируулна.",
        "ms": "Pasang dan konfigurasikan virt-manager, libvirt dan qemu.",
        "my": "virt-manager, libvirt နှင့် qemu ကို ထည့်သွင်းပြီး ပြင်ဆင်သည်။",
        "nb": "Installer og konfigurer virt-manager, libvirt og qemu.",
        "ne": "virt-manager, libvirt र qemu स्थापना र कन्फिगर गर्नुहोस्।",
        "nl": "Installeer en configureer virt-manager, libvirt en qemu.",
        "pl": "Zainstaluj i skonfiguruj virt-manager, libvirt i qemu.",
        "pt": "Instale e configure virt-manager, libvirt e qemu.",
        "ro": "Instalați și configurați virt-manager, libvirt și qemu.",
        "ru": "Установите и настройте virt-manager, libvirt и qemu.",
        "sk": "Nainštalujte a nakonfigurujte virt-manager, libvirt a qemu.",
        "sl": "Namestite in nastavite virt-manager, libvirt in qemu.",
        "sq": "Instaloni dhe konfigurojini virt-manager, libvirt dhe qemu.",
        "sr": "Инсталирајте и конфигурирајте virt-manager, libvirt и qemu.",
        "sv": "Installera och konfigurera virt-manager, libvirt och qemu.",
        "sw": "Sakinisha na kuandika virt-manager, libvirt na qemu.",
        "ta": "virt-manager, libvirt மற்றும் qemu ஐ நிறுவுங்கள் மற்றும் கட்டமைக்கவும்.",
        "tg": "virt-manager, libvirt ва qemuро насб ва танзим кунед.",
        "th": "ติดตั้งและตั้งค่า virt-manager, libvirt และ qemu",
        "tl": "Mag-install at i-configure ang virt-manager, libvirt at qemu.",
        "tr": "virt-manager, libvirt ve qemu yükleyin ve yapılandırın.",
        "uk": "Встановіть та налаштуйте virt-manager, libvirt та qemu.",
        "ur": "virt-manager, libvirt اور qemu کو انسٹال اور کنفیگر کریں۔",
        "uz": "virt-manager, libvirt va qemuни o'rnating va sozlang.",
        "vi": "Cài đặt và cấu hình virt-manager, libvirt và qemu.",
        "zh": "安装并配置 virt-manager、libvirt 和 qemu。",
    },
}

# Skip 'en' since it's already added
for key, lang_translations in translations.items():
    for lang, translation in lang_translations.items():
        file_path = os.path.join(lang_dir, f"{lang}.json")
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data[key] = translation
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Added {key} to {lang}.json")
        else:
            print(f"File {file_path} does not exist")
