import json
import os

# Directory containing the language files
lang_dir = "../p3/libs/lang/"

# Translations dictionary: key -> {lang_code: translation}
translations = {
    "needed_requirements_footer": {
        "am": "እነዚህ አስፈላጊ ባህሪዎች መጀመሪያ ይገጠሙታል፣ ከዚያ ዋናው ስክሪፕት ይቀጥላል።",
        "ar": "سيتم تثبيت هذه الميزات المطلوبة أولاً، ثم سيستمر البرنامج الرئيسي.",
        "az": "Bu tələb olunan xüsusiyyətlər əvvəlcə quraşdırılacaq, sonra əsas skript davam edəcəkdir.",
        "bg": "Тези необходими функции ще бъдат инсталирани първо, след което основният скрипт ще продължи.",
        "bn": "এই প্রয়োজনীয় বৈশিষ্ট্যগুলি প্রথমে ইনস্টল করা হবে, তারপর প্রধান স্ক্রিপ্ট চলতে থাকবে।",
        "bs": "Ove obavezne osobine će biti instalirane prvo, a zatim će glavni skript nastaviti.",
        "cs": "Tyto požadované funkce budou nainstalovány jako první, poté bude pokračovat hlavní skript.",
        "da": "Disse påkrevede funktioner vil blive installeret først, derefter vil hovedscriptet fortsætte.",
        "de": "Diese erforderlichen Funktionen werden zuerst installiert, dann wird das Hauptskript fortgesetzt.",
        "el": "Αυτές οι απαιτούμενες λειτουργίες θα εγκατασταθούν πρώτα, στη συνέχεια το κύριο σενάριο θα συνεχιστεί.",
        "es": "Estas funciones necesarias se instalarán primero, luego continuará el script principal.",
        "et": "Need nõutavad funktsioonid paigaldatakse esmalt, seejärel jätkub peamine skript.",
        "fa": "این ویژگی های مورد نیاز ابتدا نصب خواهند شد، سپس اسکریپت اصلی ادامه خواهد یافت.",
        "fi": "Nämä vaaditut ominaisuudet asennetaan ensin, minkä jälkeen pääskripti jatkuu.",
        "fr": "Ces fonctionnalités requises seront installées en premier, puis le script principal continuera.",
        "ga": "Suiteofar na gné riachtanacha seo ar dtús, ansin leanfaidh an príomhscript ar aghaidh.",
        "he": "תכונות נדרשות אלה יותקנו תחילה, ואז הסקריפט הראשי יימשך.",
        "hi": "ये आवश्यक विशेषताएं पहले स्थापित की जाएंगी, फिर मुख्य स्क्रिप्ट जारी रहेगी।",
        "hr": "Ove obavezne osobine će biti instalirane prvo, a zatim će se glavni skript nastaviti.",
        "hu": "Ezek a szükséges funkciók először telepítésre kerülnek, majd a fő szkript folytatódik.",
        "hy": "Այս անհրաժեշտ գործառույթները կտեղադրվեն առաջին հերթին, ապա հիմնական սկրիպտը կշարունակվի:",
        "id": "Fitur-fitur yang diperlukan ini akan diinstal terlebih dahulu, kemudian skrip utama akan berlanjut.",
        "is": "Þessir nauðsynlegu eiginleikar verða settir upp fyrst, síðan mun aðalskriftið halda áfram.",
        "it": "Queste funzioni necessarie verrano installate prima, quindi lo script principale continuerà.",
        "ja": "これらの必要な機能がまずインストールされ、その後、メインスクリプトが続行されます。",
        "ka": "ეს საჭირო ფუნქციები ჯერ დაინსტალირდება, შემდეგ მთავარი სკრიპტი გაგრძელდება.",
        "km": "មុខងារដែលចាំបាច់ទាំងនេះនឹងត្រូវបានដំឡើងដំបូង បន្ទាប់មក ស្គ្រីបបន្ថែមនឹងបន្ត។",
        "ko": "이러한 필수 기능이 먼저 설치되고 메인 스크립트가 계속됩니다.",
        "lo": "ຄຸນສົມບັດທີ່ຈໍາເປັນເຫຼົ່ານີ້ຈະຖືກຕິດຕັ້ງກ່ອນ, ຫຼັງຈາກນັ້ນ ສະຄິບທີ່ຕົ້ນຕໍຈະສືບຕໍ່ໄປ.",
        "lt": "Šios reikalingos funkcijos bus sumontuotos pirmiausia, tada tęsis pagrindinė skripta.",
        "lv": "Šīs nepieciešamās funkcijas tiks instalētas vispirms, tad turpināsies galvenais skripts.",
        "mn": "Эдгээр шаардлагатай функцууд эхлээд суулгагдаж, дараа нь үндсэн скрипт үргэлжлүүлнэ.",
        "ms": "Fitur-fitur yang diperlukan ini akan dipasang terlebih dahulu, kemudian skrip utama akan dilanjutkan.",
        "my": "ဤလိုအပ်သည့် အင်္ဂါရပ်များ ကို ဦးစွာ ထည့်သွင်းမည်ဖြစ်ပြီး၊ ထို့နောက် အဓိက စာသားများ သည် ဆက်လက်မည်ဖြစ်သည်။",
        "nb": "Disse nødvendige funksjonene vil bli installert først, deretter vil hovedskriptet fortsette.",
        "ne": "यी आवश्यक सुविधाहरू पहिले स्थापन गरिनेछन्, त्यसपछि मुख्य स्क्रिप्ट जारी रहनेछ।",
        "nl": "Deze vereiste functies worden eerst geïnstalleerd, waarna het hoofdscript wordt voortgezet.",
        "pl": "Te wymagane funkcje będą zainstalowane najpierw, a następnie główny skrypt będzie kontynuować.",
        "pt": "Esses recursos necessários serão instalados primeiro, depois o script principal continuará.",
        "ro": "Aceste funcții necesare vor fi instalate mai întâi, apoi scriptul principal va continua.",
        "ru": "Эти необходимые функции будут установлены в первую очередь, а затем основной скрипт продолжит работу.",
        "sk": "Tieto potrebné funkcie budú nainštalované ako prvé, potom bude pokračovať hlavný skript.",
        "sl": "Te potrebne funkcije bodo najprej nameščene, nato pa se bo glavni skript nadaljeval.",
        "sq": "Këto veçori të nevojshme do të instalohen fillimisht, pastaj skripti kryesor do të vazhdojë.",
        "sr": "Ове потребне функције ће бити инсталиране прво, а затим ће главна скрипта наставити.",
        "sv": "Dessa obligatoriska funktioner kommer att installeras först, sedan fortsätter huvudskriptet.",
        "sw": "Vipengele hivi vya mahitaji vitakamatia kwanza, kisha hati kuu itaendelea.",
        "ta": "இந்த தேவையான அம்சங்கள் முதலில் நிறுவப்படும், பிறகு முக்கிய திரைப்பதிவு தொடரும்.",
        "tg": "Ин хусусиятҳои талаботӣ аввал насб шудаанд, баъди он раёи асосӣ идома хоҳад ёфт.",
        "th": "ฟีเจอร์ที่จำเป็นเหล่านี้จะถูกติดตั้งก่อน จากนั้นสคริปต์หลักจะดำเนินการต่อ",
        "tl": "Ang mga kinakailangang feature na ito ay ilalagay muna, pagkatapos ang pangunahing script ay magpapatuloy.",
        "tr": "Bu gerekli özellikler önce yüklenecek, sonra ana betiği devam edecektir.",
        "uk": "Ці необхідні функції будуть встановлені спочатку, потім основний скрипт продовжиться.",
        "ur": "یہ ضروری خصوصیات پہلے انسٹال کی جائیں گی، پھر اہم اسکرپٹ جاری رہے گی۔",
        "uz": "Bu kerakli xususiyatlar avval o'rnatiladi, so'ng asosiy skript davom etadi.",
        "vi": "Các tính năng cần thiết này sẽ được cài đặt trước, sau đó tập lệnh chính sẽ tiếp tục.",
        "zh": "这些必需的功能将首先安装，然后主脚本将继续进行。",
    },
    "libvirt_desc": {
        "am": "virt-manager፣ libvirt እና qemu ይጭኑ እና ይዋቅሩ።",
        "ar": "تثبيت وتكوين virt-manager و libvirt و qemu.",
        "az": "virt-manager, libvirt və qemu quraşdırın və konfiqurasiya edin.",
        "bg": "Инсталирайте и конфигурирайте virt-manager, libvirt и qemu.",
        "bn": "virt-manager, libvirt এবং qemu ইনস্টল এবং কনফিগার করুন।",
        "bs": "Instalirajte i konfigurujte virt-manager, libvirt i qemu.",
        "cs": "Nainstalujte a nakonfigurujte virt-manager, libvirt a qemu.",
        "da": "Installer og konfigurer virt-manager, libvirt og qemu.",
        "de": "Installieren und konfigurieren Sie virt-manager, libvirt und qemu.",
        "el": "Εγκαταστήστε και διαμορφώστε virt-manager, libvirt και qemu.",
        "es": "Instale y configure virt-manager, libvirt y qemu.",
        "et": "Paigaldage ja konfigureerige virt-manager, libvirt ja qemu.",
        "fa": "virt-manager، libvirt و qemu را نصب و پیکربندی کنید.",
        "fi": "Asenna ja määritä virt-manager, libvirt ja qemu.",
        "fr": "Installez et configurez virt-manager, libvirt et qemu.",
        "ga": "Suiteáil agus cumraigh virt-manager, libvirt agus qemu.",
        "he": "התקן והגדר את virt-manager, libvirt ו-qemu.",
        "hi": "virt-manager, libvirt और qemu को इंस्टॉल और कॉन्फ़िगर करें।",
        "hr": "Instalirajte i konfigurujte virt-manager, libvirt i qemu.",
        "hu": "Telepítse és konfigurálja a virt-manager, libvirt és qemu alkalmazást.",
        "hy": "Տեղադրեք և կազմավորեք virt-manager, libvirt և qemu:",
        "id": "Pasang dan konfigurasikan virt-manager, libvirt, dan qemu.",
        "is": "Settu upp og stilltu virt-manager, libvirt og qemu.",
        "it": "Installa e configura virt-manager, libvirt e qemu.",
        "ja": "virt-manager、libvirt、qemuをインストールおよび構成します。",
        "ka": "დაიდეგე და გააკონფიგურე virt-manager, libvirt და qemu.",
        "km": "ដំឡើង និងកំណត់ virt-manager, libvirt និង qemu។",
        "ko": "virt-manager, libvirt 및 qemu를 설치하고 구성합니다.",
        "lo": "ຕິດຕັ້ງ ແລະ ກຳນົດຄ່າ virt-manager, libvirt ແລະ qemu.",
        "lt": "Įdiekite ir sukonfigūruokite virt-manager, libvirt ir qemu.",
        "lv": "Instalējiet un konfigurējiet virt-manager, libvirt un qemu.",
        "mn": "virt-manager, libvirt болон qemu-г суулгаж, тохируулна.",
        "ms": "Pasang dan konfigurasikan virt-manager, libvirt dan qemu.",
        "my": "virt-manager, libvirt နှင့် qemu ကို ထည့်သွင်းပြီး ပြင်ဆင်သည်။",
        "nb": "Installer og konfigurer virt-manager, libvirt og qemu.",
        "ne": "virt-manager, libvirt र qemu स्थापना र कन्फिगर गर्नुहोस्।",
        "nl": "Installeer en configureer virt-manager, libvirt en qemu.",
        "pl": "Zainstaluj i skonfiguruj virt-manager, libvirt i qemu.",
        "pt": "Instale e configure virt-manager, libvirt e qemu.",
        "ro": "Instalați și configurați virt-manager, libvirt și qemu.",
        "ru": "Установите и настройте virt-manager, libvirt и qemu.",
        "sk": "Nainštalujte a nakonfigurujte virt-manager, libvirt a qemu.",
        "sl": "Namestite in nastavite virt-manager, libvirt in qemu.",
        "sq": "Instaloni dhe konfigurojini virt-manager, libvirt dhe qemu.",
        "sr": "Инсталирајте и конфигурирајте virt-manager, libvirt и qemu.",
        "sv": "Installera och konfigurera virt-manager, libvirt och qemu.",
        "sw": "Sakinisha na kuandika virt-manager, libvirt na qemu.",
        "ta": "virt-manager, libvirt மற்றும் qemu ஐ நிறுவுங்கள் மற்றும் கட்டமைக்கவும்.",
        "tg": "virt-manager, libvirt ва qemuро насб ва танзим кунед.",
        "th": "ติดตั้งและตั้งค่า virt-manager, libvirt และ qemu",
        "tl": "Mag-install at i-configure ang virt-manager, libvirt at qemu.",
        "tr": "virt-manager, libvirt ve qemu yükleyin ve yapılandırın.",
        "uk": "Встановіть та налаштуйте virt-manager, libvirt та qemu.",
        "ur": "virt-manager, libvirt اور qemu کو انسٹال اور کنفیگر کریں۔",
        "uz": "virt-manager, libvirt va qemuни o'rnating va sozlang.",
        "vi": "Cài đặt và cấu hình virt-manager, libvirt và qemu.",
        "zh": "安装并配置 virt-manager、libvirt 和 qemu。",
    },
    "zash_desc": {
        "am": "ዘመናዊ GTK4 ተርሚናል ከላቀ ክፍለ-ጊዜ 리리ንግ እና SSH ሥራዎች ጋር።",
        "ar": "طرفية GTK4 حديثة مع إدارة جلسات متقدمة وسير عمل SSH.",
        "az": "Təkmilləşdirilmiş sesiya idarəçiliyi və SSH iş axını ilə müasır GTK4 terminalı.",
        "bg": "Модерен терминал GTK4 с напредно управление на сесии и SSH работни потоци.",
        "bn": "উন্নত সেশন ব্যবস্থাপনা এবং SSH ওয়ার্কফ্লো সহ আধুনিক GTK4 টার্মিনাল।",
        "bs": "Moderan GTK4 terminal s naprednim upravljanjem sesije i SSH radnim tokovima.",
        "cs": "Moderní GTK4 terminál s pokročilou správou relací a pracovními postupy SSH.",
        "da": "Moderno GTK4-terminal med avanceret sessionsadministration og SSH-arbejdsflow.",
        "de": "Modernes GTK4-Terminal mit fortschrittlicher Sitzungsverwaltung und SSH-Workflows.",
        "el": "Σύγχρονο τερματικό GTK4 με προηγμένη διαχείριση συνεδρίας και ροές εργασίας SSH.",
        "es": "Terminal GTK4 moderno con gestión avanzada de sesiones y flujos de trabajo SSH.",
        "et": "Kaasaegne GTK4 terminal koos täpsema istungi hallimise ja SSH töövoogudega.",
        "fa": "ترمینال GTK4 مدرن با مدیریت جلسات پیشرفته و گردش کار SSH.",
        "fi": "Moderni GTK4-pääte, jossa on kehittynyt istunnonhallinta ja SSH-työvälineet.",
        "fr": "Terminal GTK4 moderne avec gestion avancée des sessions et flux de travail SSH.",
        "ga": "Teirminéal GTK4 nua-aimseartha le bainistiú socruithe ardleibhéal agus sreafaí oibre SSH.",
        "he": "טרמינל GTK4 מודרני עם ניהול הפעלות מתקדם וזרימות עבודה SSH.",
        "hi": "उन्नत सेशन प्रबंधन और SSH वर्कफ़्लो के साथ आधुनिक GTK4 टर्मिनल।",
        "hr": "Moderni GTK4 terminal s naprednom upravom sesija i SSH radnim tokovima.",
        "hu": "Korszerű GTK4 terminál fejlett munkamenet-kezeléssel és SSH-munkafolyamatokkal.",
        "hy": "Ժամանակակա GTK4 տերմինալ՝ առաջադեմ նստեցի կառավարմամբ և SSH հոսքերով:",
        "id": "Terminal GTK4 modern dengan manajemen sesi lanjutan dan alur kerja SSH.",
        "is": "Nútímalegur GTK4 skjáherramatur með háþróaðri lotastjórnun og SSH-verkum.",
        "it": "Terminale GTK4 moderno con gestione avanzata delle sessioni e flussi di lavoro SSH.",
        "ja": "高度なセッション管理とSSHワークフロー備えた最新のGTK4ターミナル。",
        "ka": "თანამედროვე GTK4 ტერმინალი მოწინავე სესიის მართვა და SSH სამუშაო ნაკადებით.",
        "km": "ឧបករណ៍គាត់សន្ទស្ទង់ GTK4 ទំនើបដែលមាន ការគ្រប់គ្រងវិទ្យាសាលប៉ាន់ប្រមាណ និងលំហូរការងារSSH។",
        "ko": "고급 세션 관리 및 SSH 워크플로우가 포함된 최신 GTK4 터미널입니다.",
        "lo": "ປ້າຕົ້ນຕໍ GTK4 ທີ່ທັນສະ ໄວ້ຕໍ່ກັບຄຸນສົມບັດ ການຈັດການສິ່ງທີ່ກ່າວມາ ແລະ ວຽກກຳຈາກ SSH.",
        "lt": "Šiuolaikinis GTK4 terminalas su pažangiu sesijų valdymu ir SSH darbo eigomis.",
        "lv": "Moderns GTK4 terminālis ar uzlabotu sesiju pārvaldību un SSH darbplūsmām.",
        "mn": "Сесийн мэргэжлийн удирдлага болон SSH ажлын урсгалтай орчин үеийн GTK4 терминал.",
        "ms": "Terminal GTK4 moden dengan manajemen sesi canggih dan alur kerja SSH.",
        "my": "အဆင့်မြင့် အစုအဝေးစီမံခန့်ခွဲမှု နှင့် SSH အလုပ်သင်္ဘောတွေ ရှိသော ခေတ်စားသည့် GTK4 အဆုံးအဖြတ်။",
        "nb": "Moderne GTK4-terminal med avansert sesjonsstyring og SSH-arbeidsflyter.",
        "ne": "उन्नत सेशन प्रबन्धन र SSH कार्यप्रवाहको साथ आधुनिक GTK4 टर्मिनल।",
        "nl": "Moderne GTK4-terminal met geavanceerd sessiebeheer en SSH-workflows.",
        "pl": "Nowoczesny terminal GTK4 z zaawansowanym zarządzaniem sesjami i przepływami pracy SSH.",
        "pt": "Terminal GTK4 moderno com gerenciamento avançado de sessões e fluxos de trabalho SSH.",
        "ro": "Terminal GTK4 modern cu gestionare avansată a sesiunilor și fluxuri de lucru SSH.",
        "ru": "Современный терминал GTK4 с расширенным управлением сеансами и рабочими процессами SSH.",
        "sk": "Moderný terminál GTK4 s pokročilou správou relácií a pracovnými postupmi SSH.",
        "sl": "Sodoben terminal GTK4 s naprednim upravljanjem sej in delovnimi tokovi SSH.",
        "sq": "Terminal GTK4 modern me menaxhim të avancuar të seancës dhe fluxe pune SSH.",
        "sr": "Савремени GTK4 терминал с напредним управљањем сеансом и SSH радним токовима.",
        "sv": "Modernt GTK4-terminal med avancerad sessionshantering och SSH-arbetsflöden.",
        "sw": "Kituo cha haraka cha GTK4 cha kisasa kilicho na usimamizi wa jukwaa linalotumia na mtiririko wa kazi wa SSH.",
        "ta": "மேம்பட்ட அமர்வு மேலாண்மை மற்றும் SSH பணிப்பாய்களைக் கொண்ட நவீன GTK4 டெர்மினல்.",
        "tg": "Терминали GTK4 муосири бо раҳборӣ пешрафтаи сеанс ва қатъҳои кор SSH.",
        "th": "เทอร์มินัล GTK4 ที่ทันสมัยพร้อมการจัดการเซッชันขั้นสูงและเวิร์กโฟลว์ SSH",
        "tl": "Modernong terminal GTK4 na may advanced na pagsasaayos ng sesyon at SSH workflows.",
        "tr": "Gelişmiş oturum yönetimi ve SSH iş akışları ile modern GTK4 terminali.",
        "uk": "Сучасний термінал GTK4 з розширеним керуванням сеансами та SSH-робочими процесами.",
        "ur": "ترقی یافتہ سیشن مینجمنٹ اور SSH ورک فلو کے ساتھ جدید GTK4 ٹرمینل۔",
        "uz": "Peshqadamiy seans boshqaruvi va SSH ish oqimlari bilan zamonaviy GTK4 terminali.",
        "vi": "Terminal GTK4 hiện đại với quản lý phiên nâng cao và quy trình công việc SSH.",
        "zh": "具有高级会话管理和 SSH 工作流的现代 GTK4 终端。",
    },
    "kind_desc": {
        "am": "ለአካባቢ Kubernetes ልማት ጅምር kind እና kubectl ማዋቀር።",
        "ar": "إعداد البداية مع kind و kubectl لتطوير Kubernetes المحلي.",
        "az": "Yerli Kubernetes inkişafı üçün başlanğıc kind və kubectl quraşdırması.",
        "bg": "Начално конфигуриране на kind и kubectl за локална разработка на Kubernetes.",
        "bn": "স্থানীয় Kubernetes উন্নয়নের জন্য স্টার্টার kind এবং kubectl সেটআপ।",
        "bs": "Početna vrsta i kubectl postavka za lokalnu Kubernetes razvoj.",
        "cs": "Úvodní nastavení kind a kubectl pro lokální vývoj Kubernetes.",
        "da": "Starteropsætning af kind og kubectl til lokal Kubernetes-udvikling.",
        "de": "Starter-Setup für kind und kubectl für die lokale Kubernetes-Entwicklung.",
        "el": "Ρύθμιση εκκίνησης kind και kubectl για τοπική ανάπτυξη Kubernetes.",
        "es": "Configuración de inicio de kind y kubectl para desarrollo local de Kubernetes.",
        "et": "Algse kind ja kubectl seadistus kohalikule Kubernetes arendusele.",
        "fa": "تنظیم kind و kubectl برای توسعه محلی Kubernetes.",
        "fi": "Perustava kind- ja kubectl-määritys paikalliselle Kubernetes-kehitykselle.",
        "fr": "Configuration de démarrage de kind et kubectl pour le développement Kubernetes local.",
        "ga": "Socrú tosaigh kind agus kubectl do fhorbairt Kubernetes áitiúil.",
        "he": "הגדרת התחלה של kind ו-kubectl לפיתוח Kubernetes מקומי.",
        "hi": "स्थानीय Kubernetes विकास के लिए स्टार्टर kind और kubectl सेटअप।",
        "hr": "Početna postavka kind i kubectl za lokalnu razvojnu Kubernetes.",
        "hu": "Startercél és kubectl beállítás a helyi Kubernetes fejlesztéshez.",
        "hy": "Starter kind և kubectl կազմավորում տեղական Kubernetes զարգացման համար:",
        "id": "Pengaturan pemula kind dan kubectl untuk pengembangan Kubernetes lokal.",
        "is": "Hafta kind og kubectl uppsetning fyrir staðbundna Kubernetes þróun.",
        "it": "Impostazione iniziale di kind e kubectl per lo sviluppo Kubernetes locale.",
        "ja": "ローカルKubernetes開発用のスターターkindとkubectlセットアップ。",
        "ka": "საწყის kind და kubectl დაყენება ადგილობრივი Kubernetes განვითარებისთვის.",
        "km": "ការដំឡើងដំបូង kind និង kubectl សម្រាប់ការអភិវឌ្ឍន៍ Kubernetes ក្នុងស្រុក។",
        "ko": "로컬 Kubernetes 개발을 위한 스타터 kind 및 kubectl 설정입니다.",
        "lo": "ການຕິດຕັ້ງ kind ແລະ kubectl ສຳລັບການພັດທະນາ Kubernetes ທ້ອງຖິ່ນ.",
        "lt": "Pradinio kind ir kubectl nustatymo skirtas vietiniam Kubernetes kūrimui.",
        "lv": "Starta kind un kubectl iestatīšana lokālai Kubernetes izstrādei.",
        "mn": "Үндэсний Kubernetes хөгжүүлэлтийн төлөөлөл kind болон kubectl байрлалын тохирол.",
        "ms": "Pengaturan pemula kind dan kubectl untuk pengembangan Kubernetes lokal.",
        "my": "ဒေသည Kubernetes တီထွင်မှုအတွက် စတင်သည့် kind နှင့် kubectl သတ်မှတ်ချက်။",
        "nb": "Starters kind og kubectl-oppsett for lokal Kubernetes-utvikling.",
        "ne": "स्थानीय Kubernetes विकास को लागि स्टार्टर kind र kubectl सेटअप।",
        "nl": "Starter kind en kubectl instelling voor lokale Kubernetes-ontwikkeling.",
        "pl": "Początkowa konfiguracja kind i kubectl do lokalnego rozwoju Kubernetes.",
        "pt": "Configuração inicial de kind e kubectl para desenvolvimento local do Kubernetes.",
        "ro": "Configurație de început kind și kubectl pentru dezvoltarea locală Kubernetes.",
        "ru": "Начальная конфигурация kind и kubectl для локальной разработки Kubernetes.",
        "sk": "Úvodná konfigurácia kind a kubectl pre lokálny vývoj Kubernetes.",
        "sl": "Začetni kind in kubectl nastavi za lokalni razvoj Kubernetes.",
        "sq": "Vendosja e fillimit të kind dhe kubectl për zhvillimin lokal të Kubernetes.",
        "sr": "Почетна врста и kubectl постава за локални развој Kubernetes.",
        "sv": "Starterkonfiguration av kind och kubectl för lokal Kubernetes-utveckling.",
        "sw": "Mpango wa kuanza kwa kind na kubectl kwa maendeleo ya Kubernetes ya ndani.",
        "ta": "உள்ளூர் Kubernetes வளர்ச்சிக்கான ஸ்டார்டர் kind மற்றும் kubectl அமைப்பு।",
        "tg": "Қарор kind ва kubectl барои рушди Kubernetes маҳаллӣ.",
        "th": "การตั้งค่าเริ่มต้น kind และ kubectl สำหรับการพัฒนา Kubernetes ในท้องถิ่น",
        "tl": "Starter kind at kubectl setup para sa lokal na pag-unlad ng Kubernetes.",
        "tr": "Yerel Kubernetes geliştirme için başlatıcı kind ve kubectl kurulumu.",
        "uk": "Стартова конфігурація kind та kubectl для локальної розробки Kubernetes.",
        "ur": "مقامی Kubernetes ترقی کے لیے سٹارٹر kind اور kubectl سیٹ اپ۔",
        "uz": "Mahalliy Kubernetes ishlab chiqish uchun starter kind va kubectl sozlamasi.",
        "vi": "Cài đặt kind và kubectl bắt đầu cho phát triển Kubernetes cục bộ.",
        "zh": "本地 Kubernetes 开发的启动 kind 和 kubectl 设置。",
    },
    "hiddify_desc": {
        "am": "Hiddify VPN ক্লায়েন্ট।",
        "ar": "عميل Hiddify VPN.",
        "az": "Hiddify VPN müştərisi.",
        "bg": "Клиент Hiddify VPN.",
        "bn": "Hiddify VPN ক্লায়েন্ট।",
        "bs": "Hiddify VPN klijent.",
        "cs": "Klient Hiddify VPN.",
        "da": "Hiddify VPN-klient.",
        "de": "Hiddify VPN-Client.",
        "el": "Πελάτης Hiddify VPN.",
        "es": "Cliente Hiddify VPN.",
        "et": "Hiddify VPN klient.",
        "fa": "کلاینت Hiddify VPN.",
        "fi": "Hiddify VPN-asiakas.",
        "fr": "Client Hiddify VPN.",
        "ga": "Cliant Hiddify VPN.",
        "he": "לקוח Hiddify VPN.",
        "hi": "Hiddify VPN क्लायंट।",
        "hr": "Hiddify VPN klijent.",
        "hu": "Hiddify VPN kliens.",
        "hy": "Hiddify VPN հաճախորդ:",
        "id": "Klien Hiddify VPN.",
        "is": "Hiddify VPN biðlari.",
        "it": "Client Hiddify VPN.",
        "ja": "Hiddify VPNクライアント。",
        "ka": "Hiddify VPN კლიენტი.",
        "km": "ក្រុមហ៊ុន Hiddify VPN.",
        "ko": "Hiddify VPN 클라이언트입니다.",
        "lo": "ລູກຄ້າ Hiddify VPN.",
        "lt": "Hiddify VPN klientas.",
        "lv": "Hiddify VPN klients.",
        "mn": "Hiddify VPN үйлчлүүлэгч.",
        "ms": "Klien Hiddify VPN.",
        "my": "Hiddify VPN အကောင်အထည်။",
        "nb": "Hiddify VPN-klient.",
        "ne": "Hiddify VPN क्लायन्ट।",
        "nl": "Hiddify VPN-client.",
        "pl": "Klient Hiddify VPN.",
        "pt": "Cliente Hiddify VPN.",
        "ro": "Client Hiddify VPN.",
        "ru": "Клиент Hiddify VPN.",
        "sk": "Klient Hiddify VPN.",
        "sl": "Odjemalec Hiddify VPN.",
        "sq": "Klient Hiddify VPN.",
        "sr": "Хиддифи ВПН клијент.",
        "sv": "Hiddify VPN-klient.",
        "sw": "Mteja wa Hiddify VPN.",
        "ta": "Hiddify VPN கிளையன்ட்.",
        "tg": "Мизоҷи Hiddify VPN.",
        "th": "ไคลเอนต์ Hiddify VPN",
        "tl": "Kliyente ng Hiddify VPN.",
        "tr": "Hiddify VPN istemcisi.",
        "uk": "Клієнт Hiddify VPN.",
        "ur": "Hiddify VPN کلائنٹ۔",
        "uz": "Hiddify VPN mijozi.",
        "vi": "Máy khách Hiddify VPN.",
        "zh": "Hiddify VPN 客户端。",
    },
    "term_view_copy": {
        "am": "አউትपুට ሎግ ቅጂ",
        "ar": "نسخ سجل الإخراج",
        "az": "Çıxış Jurnalını Kopyala",
        "bg": "Копиране на журнала на изхода",
        "bn": "আউটপুট লগ অনুলিপি করুন",
        "bs": "Kopiraj izlazni dnevnik",
        "cs": "Kopírovat výstupní protokol",
        "da": "Kopiér outputlog",
        "de": "Ausgabeprotokoll kopieren",
        "el": "Αντιγραφή αρχείου καταγραφής εξόδου",
        "es": "Copiar registro de salida",
        "et": "Väljund logi kopeerimine",
        "fa": "کپی کردن سیاق خروجی",
        "fi": "Kopioi tulostuslokin",
        "fr": "Copier le journal de sortie",
        "ga": "Cóipeáil an logchomhad aschuir",
        "he": "העתק את ההתחברות למוצא",
        "hi": "आउटपुट लॉग कॉपी करें",
        "hr": "Kopiraj izlazni dnevnik",
        "hu": "Kimeneti napló másolása",
        "hy": "Պատճենել արտադրանքի տեղեկամատյան:",
        "id": "Salin Log Output",
        "is": "Afrita útfærslu annál",
        "it": "Copia registro di output",
        "ja": "出力ログをコピー",
        "ka": "გამოსახვის ჟურნალის კოპირება",
        "km": "ចម្លងកាលបរិច្ឆេទលទ្ធផល",
        "ko": "출력 로그 복사",
        "lo": "ສໍາເນົາ ບັນທຶກວຽກ",
        "lt": "Kopijuoti išvesties žurnalą",
        "lv": "Kopēt izslēgšanas žurnālu",
        "mn": "Гамма гадсын логыг хуулах",
        "ms": "Salin Log Output",
        "my": "အထွက်လုံးချင်းယူခြင်း",
        "nb": "Kopier utdatalogg",
        "ne": "आउटपुट लग प्रतिलिपि गर्नुहोस्",
        "nl": "Uitvoerlogboek kopiëren",
        "pl": "Skopiuj dziennik wyjścia",
        "pt": "Copiar log de saída",
        "ro": "Copiare jurnal de ieșire",
        "ru": "Копировать журнал вывода",
        "sk": "Kopírovat výstupný protokol",
        "sl": "Kopiraj izhodny dnevnik",
        "sq": "Kopjo regjistrin e daljes",
        "sr": "Копирај излазни дневник",
        "sv": "Kopiera utdatalogg",
        "sw": "Nakili Kumbukumbu ya Matokeo",
        "ta": "வெளியீட்டு பதிவைப் பிரতிலிபி செய்யுங்கள்",
        "tg": "Қайд ҳуҷҷаа даромади",
        "th": "คัดลอกบันทึกผลลัพธ์",
        "tl": "Kopyahin ang Output Log",
        "tr": "Çıktı Günlüğünü Kopyala",
        "uk": "Копіювати журнал вихідних даних",
        "ur": "آؤٹ پٹ لاگ کاپی کریں",
        "uz": "Chiqish jurnalini nusxa qiling",
        "vi": "Sao chép nhật ký đầu ra",
        "zh": "复制输出日志",
    },
}

# Skip 'en' since it's already added
for key, lang_translations in translations.items():
    for lang, translation in lang_translations.items():
        file_path = os.path.join(lang_dir, f"{lang}.json")
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data[key] = translation
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Added {key} to {lang}.json")
        else:
            print(f"File {file_path} does not exist")
